"""describe your changes here

Revision ID: d9650e2407dc
Revises: 1f8a6b2ae418
Create Date: 2025-06-07 11:31:01.504546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9650e2407dc'
down_revision = '1f8a6b2ae418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_public_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('profile_picture_public_id')

    # ### end Alembic commands ###
